sequenceDiagram
    participant U as Tyrėjas
    participant J as Joern
    participant CPG as CPG
    participant CSV as CSV

    U->>J: Įkeliami failai
    J->>CPG: Kodo grafo paruošimas

    U->>J: Išrūšiuojami metodai
    J->>CPG: Analizuojami metodai

    loop Kiekvienam metodui
        J->>CPG: AST / CFG / PDG analizė
        J-->>J: Savybių skaičiavimas
    end

    J->>CSV: Savybių vektoriai
