flowchart TB

A1[AST analizė]

A2[CFG analizė]

A3[PDG analizė]

B1[Scala ir Joern pagrindai]

B2[Joern sistemos paruošimas
CPG generavimas]

C1[Juliet Test Suite analizė ir pažeidžiamumų pasirinkimas]

C2[Analizuojamos CWE klasės
CWE121_Stack_Based_Buffer_Overflow
CWE122_Heap_Based_Buffer_Overflow
CWE124_Buffer_Underwrite
CWE126_Buffer_Overread
CWE127_Buffer_Underread
CWE134_Uncontrolled_Format_String
CWE415_Double_Free
CWE416_Use_After_Free
CWE426_Untrusted_Search_Path
CWE427_Uncontrolled_Search_Path_Element
CWE680_Integer_Overflow_to_Buffer_Overflow
CWE78_OS_Command_Injection]

C3[Atskira analizė kiekvienai CWE
Vienas .ipynb failas]

D1[C kodo analizė naudojant Joern]

D2[Funkcijų ištraukimas iš failų]

D3[Automatinis žymėjimas
good = 0
bad = 1]

E1[AST požymiai
ast_nodes
call_count
identifier_count
literal_count
max_ast_depth
input_call_count
conversion_call_count
memory_call_count
exec_call_count
format_call_count
calls_per_ast_node
]

E2[CFG požymiai
control_count
branch_count
loop_count
return_count
cyclomatic_complexity
sink_inside_loop]

E3[PDG požymiai
pointer_identifier_count
address_of_count
bounds_check_count
null_check_count
array_write_count
sink_call_count
taint_reachable
def_count
use_count
checks_per_sink]

F1[Savybių vektorių sudarymas]

F2[CSV failų generavimas
Atskiras failas kiekvienai CWE]

F3[Konstantinių savybių šalinimas]

F4[Mokymo ir testavimo aibės padalijimas]

G1[Linear Regression]

G2[Random Forest]

H2[Modelių palyginimas]

J1[Svarbiausių savybių atranka]

J2[Dydžio savybių pašalinimas]

J3[Pakartotinis mokymas
Pakartotinis vertinimas]

A1 --> B1
A2 --> B1
A3 --> B1

B1 --> B2
B2 --> C1

C1 --> C2
C2 --> C3

C3 --> D1
D1 --> D2
D2 --> D3

D3 --> E1
D3 --> E2
D3 --> E3

E1 --> F1
E2 --> F1
E3 --> F1

F1 --> F2
F2 --> F3
F3 --> F4

F4 --> G1
F4 --> G2

G1 --> H2
G2 --> H2

H2 --> J1
J1 --> J2
J2 --> J3
