---
config:
  layout: fixed
---
flowchart TB
    A["Teorija<br>AST / CFG / PDG"] --> B["Įrankiai<br>Joern + CPG"]
    B --> C["Duomenys<br>Juliet Test Suite"]
    C --> D["Kodo analizė<br>Funkcijų lygmuo"]
    D --> E["Savybių išgavimas<br>AST / CFG / PDG"]
    E --> F["Savybių matrica<br>CSV"]
    F --> G["Mašininis mokymas<br>LR, RF"]
    G --> H["Rezultatų analizė<br>Modelių palyginimas"]
    H --> I["Išvados ir rekomendacijos<br>Praktinis taikymas"]